### ISSUE TITLE
Need fine tuning?

### ISSUE THREAD

**Issue by aungpaing98** [mmaaz60/mdef_detr#1]
First of all, Congrats on such a great work.
And I would like to test with fine tuning the minus-language model to custom data set.

I have tried with run_with_submitit.py, but it does not train and seems like it only assign job for submitit.

I am not very familiar with submitit, but could you share some way which I could do fine tuning.

Thanks again.

**Comment by mmaaz60** [comment]
Hi @aungpaing98,

In order to fine-tune MDef-DETR Minus-Language model (equivalent to Def-DETR) using this repository, you need to convert your dataset into MDETR pretraining data format. Or otherwise, you will be modifying/writing your own data loader.

Further, you can also use the below simple SLURM script for running trainings.

```
#!/bin/sh
#SBATCH --job-name=<job_name>
#SBATCH --partition=<partition_name
#SBATCH --time=72:00:00
#SBATCH --nodes=8
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=10
#SBATCH --gres=4
#SBATCH --mem-per-cpu=8000

srun python main.py --dataset_config configs/pretrain.json --ema --output-dir ./checkpoints/
```

Please have look at the `main.py` script if you are not using SLURM cluster for training. I hope this will help.

Further, please have a look at our [main repository](https://github.com/mmaaz60/mvits_for_class_agnostic_od) for evaluating pretrained MDef-DETR model on your custom dataset.

Thank you

**Comment by aungpaing98** [comment]
@mmaaz60 , Thanks you so much for your explanation.
I will check that.

Sorry, just one more question,
Does that mean if we only need to do class-aware object detection,
using Def-DETR model will be the same?

**Comment by mmaaz60** [comment]
> @mmaaz60 , Thanks you so much for your explanation. I will check that.
> 
> Sorry, just one more question, Does that mean if we only need to do class-aware object detection, using Def-DETR model will be the same?

Hi @aungpaing98,

The `MDef-DETR minus Language` model is nothing but `single-class Def-DETR` trained using `MDETR data loader` (i.e. keeping the structure introduced by 1.3M captions intact).

**Comment by aungpaing98** [comment]
Thanks for your answer.
